/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package InformeRendimientoAcademico;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sistemadegestionacademica.Estudiante;
import sistemadegestionacademica.Grado;

/**
 *
 * @author nothing
 */
public class IFrmRendimiento extends javax.swing.JInternalFrame {

    /**
     * Creates new form IFrmRendimiento
     */
    DefaultTableModel modeloTabla;
    public IFrmRendimiento() {
        initComponents();
        String [] encabezado = {"Estudiante","Grado","Promedio","Estado"};
        modeloTabla = new DefaultTableModel(encabezado,0);
        jTable1.setModel(modeloTabla);
        txtNotaMinima.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNotaMinima = new javax.swing.JTextField();
        btnMostrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);

        txtNotaMinima.setText("jTextField1");

        btnMostrar.setText("Mostrar informe");
        btnMostrar.addActionListener(this::btnMostrarActionPerformed);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Ingrese la nota minima para pasar:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNotaMinima, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMostrar))
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNotaMinima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMostrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        // TODO add your handling code here:
        mostrarRendimiento();
    }//GEN-LAST:event_btnMostrarActionPerformed

    public void mostrarRendimiento(){
        String texto = txtNotaMinima.getText().trim();

        if (texto.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Escriba la nota mínima para aprobar");
            return;
        }

        double notaMinima;
        try {
            notaMinima = Double.parseDouble(texto);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "La nota debe ser un número");
            return;
        }
        if (notaMinima < 0 || notaMinima > 5) {
            JOptionPane.showMessageDialog(this, "La nota debe estar entre 0 y 5");
            return;
        }

        if (Grado.obtenerEstudiantes().isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay estudiantes registrados");
            return;
        }

        modeloTabla.setRowCount(0);
        for (Estudiante e : Grado.obtenerEstudiantes()) {
            double promedio = Math.round(e.calcularPromedio() * 100.0) / 100.0;
            String estado;
            if (e.aprobo(notaMinima)) {
                estado = "Aprobó";
            } else {
                estado = "Reprobó";
            }
            modeloTabla.addRow(new Object[]{
                e.getNombreEstudiante(), e.getGradoEstudiante(), promedio, estado
            });
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMostrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtNotaMinima;
    // End of variables declaration//GEN-END:variables
}
