/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistemadegestionacademica;
import InformeEstudiantesPorGrado.IFrmEstudiantesPorGrado;
import InformeCalificaciones.IframeCalificaciones;
import InformeRendimientoAcademico.IFrmRendimiento;
import javax.swing.JOptionPane;
/**
 *
 * @author Usuario
 */
public class FrmMain extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmMain.class.getName());

    /**
     * Creates new form Main
     */
    int id,profile;
    String user;
    public FrmMain(int id,int profile,String user) {
        this.id = id;
        this.profile = profile;
        this.user = user;
        initComponents();
        
        if(profile == 1){
            menuAdministrar.setVisible(true);
        }else{
            menuAdministrar.setVisible(false);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopMain = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuEstudiantesPorGrado = new javax.swing.JMenuItem();
        menuCalificaciones = new javax.swing.JMenuItem();
        menuRendimiento = new javax.swing.JMenuItem();
        menuCerrarSesion = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuAdministrar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout desktopMainLayout = new javax.swing.GroupLayout(desktopMain);
        desktopMain.setLayout(desktopMainLayout);
        desktopMainLayout.setHorizontalGroup(
            desktopMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 675, Short.MAX_VALUE)
        );
        desktopMainLayout.setVerticalGroup(
            desktopMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 389, Short.MAX_VALUE)
        );

        jMenu1.setText("File");

        menuEstudiantesPorGrado.setText("EstudiantesPorGrado");
        menuEstudiantesPorGrado.addActionListener(this::menuEstudiantesPorGradoActionPerformed);
        jMenu1.add(menuEstudiantesPorGrado);

        menuCalificaciones.setText("Calificaciones");
        menuCalificaciones.addActionListener(this::menuCalificacionesActionPerformed);
        jMenu1.add(menuCalificaciones);

        menuRendimiento.setText("Rendimiento");
        menuRendimiento.addActionListener(this::menuRendimientoActionPerformed);
        jMenu1.add(menuRendimiento);

        menuCerrarSesion.setText("Cerrar Sesion");
        menuCerrarSesion.addActionListener(this::menuCerrarSesionActionPerformed);
        jMenu1.add(menuCerrarSesion);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        menuAdministrar.setText("Administrar");
        menuAdministrar.addActionListener(this::menuAdministrarActionPerformed);
        jMenu2.add(menuAdministrar);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopMain)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopMain)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    private void menuEstudiantesPorGradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEstudiantesPorGradoActionPerformed
        // TODO add your handling code here:
        IFrmEstudiantesPorGrado InformePorGrado = new IFrmEstudiantesPorGrado();
        desktopMain.add(InformePorGrado);
        InformePorGrado.show();
        
    }//GEN-LAST:event_menuEstudiantesPorGradoActionPerformed

    private void menuAdministrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAdministrarActionPerformed
        // TODO add your handling code here:
        IFrmAdministrar administrar = new IFrmAdministrar();
        desktopMain.add(administrar);
        administrar.show();
        
    }//GEN-LAST:event_menuAdministrarActionPerformed

    private void menuCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCerrarSesionActionPerformed
        // TODO add your handling code here:
        FrmLogin login = new FrmLogin();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuCerrarSesionActionPerformed

    private void menuCalificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCalificacionesActionPerformed
        // TODO add your handling code here:
        IframeCalificaciones calificaciones = new IframeCalificaciones();
        desktopMain.add(calificaciones);
        calificaciones.show();
    }//GEN-LAST:event_menuCalificacionesActionPerformed

    private void menuRendimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRendimientoActionPerformed
        // TODO add your handling code here:
        IFrmRendimiento rendimiento = new IFrmRendimiento();
        desktopMain.add(rendimiento);
        rendimiento.show();
        
    }//GEN-LAST:event_menuRendimientoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmMain(0,0,"").setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopMain;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuAdministrar;
    private javax.swing.JMenuItem menuCalificaciones;
    private javax.swing.JMenuItem menuCerrarSesion;
    private javax.swing.JMenuItem menuEstudiantesPorGrado;
    private javax.swing.JMenuItem menuRendimiento;
    // End of variables declaration//GEN-END:variables
}
