/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package sistemadegestionacademica;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author nothing
 */
public class IFrmAdministrar extends javax.swing.JInternalFrame {

    /**
     * Creates new form IFrmAdministrar
     */
    
    DefaultTableModel modeloTabla;
    public IFrmAdministrar() {
        initComponents();
        String [] encabezado = {"Estudiante","Grado","Asignatura","periodo","Nota"};
        modeloTabla = new DefaultTableModel(encabezado,0);
        jTable1.setModel(modeloTabla);
        txtNombreEstudiante.setText("");
        txtValor.setText("");
        llenarCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GradoEs = new javax.swing.ButtonGroup();
        Periodo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtNombreEstudiante = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        comboAsignaturas = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        rbtnGrado1 = new javax.swing.JRadioButton();
        rbtnGrado2 = new javax.swing.JRadioButton();
        rbtnGrado3 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        rbtnPeriodo1 = new javax.swing.JRadioButton();
        rbtnPeriodo2 = new javax.swing.JRadioButton();
        rbtnPeriodo3 = new javax.swing.JRadioButton();

        setClosable(true);

        jLabel1.setText("Nombre Estudiante:");

        txtNombreEstudiante.setText("jTextField1");

        jLabel2.setText("Asignatura:");

        comboAsignaturas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Grado:");

        GradoEs.add(rbtnGrado1);
        rbtnGrado1.setText("Grado 1");

        GradoEs.add(rbtnGrado2);
        rbtnGrado2.setText("Grado 2");

        GradoEs.add(rbtnGrado3);
        rbtnGrado3.setText("Grado 3");

        jLabel4.setText("Valor");

        txtValor.setText("jTextField1");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(this::btnAgregarActionPerformed);

        jLabel5.setText("Periodo");

        Periodo.add(rbtnPeriodo1);
        rbtnPeriodo1.setText("Periodo 1");

        Periodo.add(rbtnPeriodo2);
        rbtnPeriodo2.setText("Periodo 2");

        Periodo.add(rbtnPeriodo3);
        rbtnPeriodo3.setText("Periodo 3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtNombreEstudiante)
                                    .addComponent(jLabel4)
                                    .addComponent(btnAgregar)
                                    .addComponent(txtValor))
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbtnGrado3)
                                    .addComponent(rbtnGrado2)
                                    .addComponent(jLabel3)
                                    .addComponent(rbtnGrado1)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(rbtnPeriodo3)
                                        .addComponent(rbtnPeriodo1)
                                        .addComponent(rbtnPeriodo2))))
                            .addComponent(comboAsignaturas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombreEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbtnGrado1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbtnGrado2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbtnGrado3)
                            .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(comboAsignaturas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAgregar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(rbtnPeriodo1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbtnPeriodo2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbtnPeriodo3))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        guardarDatos();
        Limpiar();
    }//GEN-LAST:event_btnAgregarActionPerformed
    
    public void guardarDatos(){
        String nombre = txtNombreEstudiante.getText().trim();
        String Valor = txtValor.getText().trim();
        
        String grado = null;
        
        if(rbtnGrado1.isSelected()){
            grado = "Grado 1";
        }else if(rbtnGrado2.isSelected()){
            grado = "Grado 2";
        }else if(rbtnGrado3.isSelected()){
            grado = "Grado 3";
        } 
        String periodo = null;
        if (rbtnPeriodo1.isSelected()) {
            periodo = "Periodo 1";
        } else if (rbtnPeriodo2.isSelected()) {
            periodo = "Periodo 2";
        } else if (rbtnPeriodo3.isSelected()) {
            periodo = "Periodo 3";
        }
        
        if (nombre.isEmpty() || grado == null ||periodo == null|| Valor.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Complete todos los campos");
            return;
        }
        
        if (comboAsignaturas.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Seleccione una asignatura ");
            return;
        }
        
        String asignatura = String.valueOf(comboAsignaturas.getSelectedItem());
        
        double valor;
        try {
            valor = Double.parseDouble(Valor);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "La nota debe ser un número");
            return;
        }
        if (valor < 0 || valor > 5) {
            JOptionPane.showMessageDialog(this, "La nota debe estar entre 0 y 5");
            return;
        }
        
        Estudiante e = Grado.buscarPorNombre(nombre);
        if (e == null) {
            e = Grado.crearEstudiante(nombre, grado);
        }

        e.agregarNota(asignatura, periodo, valor);            
        JOptionPane.showMessageDialog(this, "Nota Agregada");

        modeloTabla.addRow(new Object[]{nombre,grado,asignatura,periodo,valor});
    }
    
    public void Limpiar(){
        txtValor.setText("");
        comboAsignaturas.setSelectedIndex(0);
        
    }
    
    private void llenarCombo(){
        comboAsignaturas.removeAllItems();
        comboAsignaturas.addItem("Seleccione...");
        
        for (String a : Grado.asignaturas) {
            comboAsignaturas.addItem(a);
        }
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GradoEs;
    private javax.swing.ButtonGroup Periodo;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JComboBox<String> comboAsignaturas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton rbtnGrado1;
    private javax.swing.JRadioButton rbtnGrado2;
    private javax.swing.JRadioButton rbtnGrado3;
    private javax.swing.JRadioButton rbtnPeriodo1;
    private javax.swing.JRadioButton rbtnPeriodo2;
    private javax.swing.JRadioButton rbtnPeriodo3;
    private javax.swing.JTextField txtNombreEstudiante;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
