/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InformeEstudiantesPorGrado;

import sistemadegestionacademica.FrmMain;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class FrmEstudiantesPorGrado extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmEstudiantesPorGrado.class.getName());
    
    DefaultTableModel modeloTabla;
    /**
     * Creates new form FrmEstudiantesPorGrado
     */
    int id, profile;
    String user;
    public FrmEstudiantesPorGrado(int id, int profile,String user) {
        
        
        this.id = id;
        this.profile = profile;
        this.user = user;
        initComponents();
        String [] encabezado = {"Estudiante","Grado"};
        modeloTabla = new DefaultTableModel(encabezado,0);
        jTable1.setModel(modeloTabla);
        txtNombreEstudiante.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GradoEstudiante = new javax.swing.ButtonGroup();
        BuscarGrado = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtNombreEstudiante = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        rbtnGrado1Estudiante = new javax.swing.JRadioButton();
        rbtnGrado2Estudiante = new javax.swing.JRadioButton();
        rbtnGrado3Estudiante = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        rbtnBuscarGrado1 = new javax.swing.JRadioButton();
        rbtnBuscarGrado2 = new javax.swing.JRadioButton();
        rbtnBuscarGrado3 = new javax.swing.JRadioButton();
        btnGuardar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Nombre del Estudiante");

        txtNombreEstudiante.setText("jTextField1");

        jLabel2.setText("Grado del Estudiante");

        GradoEstudiante.add(rbtnGrado1Estudiante);
        rbtnGrado1Estudiante.setText("Grado 1");

        GradoEstudiante.add(rbtnGrado2Estudiante);
        rbtnGrado2Estudiante.setText("Grado 2");

        GradoEstudiante.add(rbtnGrado3Estudiante);
        rbtnGrado3Estudiante.setText("Grado 3");

        jLabel3.setText("Seleccione el grado a buscar");

        BuscarGrado.add(rbtnBuscarGrado1);
        rbtnBuscarGrado1.setText("Grado 1");

        BuscarGrado.add(rbtnBuscarGrado2);
        rbtnBuscarGrado2.setText("Grado 2");

        BuscarGrado.add(rbtnBuscarGrado3);
        rbtnBuscarGrado3.setText("Grado 3");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(this::btnRegresarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtnGrado3Estudiante)
                    .addComponent(btnGuardar)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNombreEstudiante))
                            .addComponent(jLabel2)
                            .addComponent(rbtnGrado1Estudiante)
                            .addComponent(rbtnGrado2Estudiante))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBuscar)
                            .addComponent(rbtnBuscarGrado3)
                            .addComponent(rbtnBuscarGrado2)
                            .addComponent(jLabel3)
                            .addComponent(rbtnBuscarGrado1)))
                    .addComponent(btnRegresar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 13, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombreEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbtnBuscarGrado1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(rbtnBuscarGrado2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbtnGrado1Estudiante)
                            .addComponent(rbtnBuscarGrado3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbtnGrado2Estudiante)
                            .addComponent(btnBuscar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtnGrado3Estudiante)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegresar)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        String nombre = txtNombreEstudiante.getText();
        String grado = null;
        
        if(rbtnGrado1Estudiante.isSelected()){
            grado = "Grado 1";
        }else if(rbtnGrado2Estudiante.isSelected()){
            grado = "Grado 2";
        }else if(rbtnGrado3Estudiante.isSelected()){
            grado = "Grado 3";
        }
        
        if(nombre.isEmpty() || grado == null){
            JOptionPane.showMessageDialog(this, "Los campos no pueden estar vacios o sin seleccion");
            return;
        }
        Grado.crearEstudiante(nombre, grado);
        JOptionPane.showMessageDialog(this, "Estudiante agregado");
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        if(rbtnBuscarGrado1.isSelected()){
            mostrarEstudiantesPorGrado("Grado 1");
        }else if(rbtnBuscarGrado2.isSelected()){
            mostrarEstudiantesPorGrado("Grado 2");
        }else if(rbtnBuscarGrado3.isSelected()){
            mostrarEstudiantesPorGrado("Grado 3");
        }else {
            JOptionPane.showMessageDialog(this, "Seleccione un Grado a buscar");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        FrmMain newframe = new FrmMain(this.id, this.profile, this.user);
        newframe.setVisible(true);
        this.dispose();
        
        
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        cerrarSesion();
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

        // TODO add your handling code here:
       
    }//GEN-LAST:event_formWindowClosed
    private void cerrarSesion(){
        FrmMain newframe = new FrmMain(this.id, this.profile, this.user);
        newframe.setVisible(true);

    }
    private void mostrarEstudiantesPorGrado(String nombreGrado){
        modeloTabla.setRowCount(0);
        List<Estudiante> filtrado = Grado.filtrarPorGrado(nombreGrado);
        
        for (Estudiante e : filtrado) {
            modeloTabla.addRow(new Object []{e.getNombreEstudiante(),e.getGradoEstudiante()});
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmEstudiantesPorGrado(0,0,"").setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BuscarGrado;
    private javax.swing.ButtonGroup GradoEstudiante;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton rbtnBuscarGrado1;
    private javax.swing.JRadioButton rbtnBuscarGrado2;
    private javax.swing.JRadioButton rbtnBuscarGrado3;
    private javax.swing.JRadioButton rbtnGrado1Estudiante;
    private javax.swing.JRadioButton rbtnGrado2Estudiante;
    private javax.swing.JRadioButton rbtnGrado3Estudiante;
    private javax.swing.JTextField txtNombreEstudiante;
    // End of variables declaration//GEN-END:variables
}
