/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package InformeEstudiantesPorGrado;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sistemadegestionacademica.Estudiante;
import sistemadegestionacademica.Grado;
/**
 *
 * @author nothing
 */
public class IFrmEstudiantesPorGrado extends javax.swing.JInternalFrame {

    /**
     * Creates new form IFrmEstudiantesPorGrado
     */
    DefaultTableModel modeloTabla;
    public IFrmEstudiantesPorGrado() {
        initComponents();
        String [] encabezado = {"Estudiante","Grado"};
        modeloTabla = new DefaultTableModel(encabezado,0);
        jTable1.setModel(modeloTabla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GradoEstudiante = new javax.swing.ButtonGroup();
        BuscarGrado = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        rbtnBuscarGrado1 = new javax.swing.JRadioButton();
        rbtnBuscarGrado2 = new javax.swing.JRadioButton();
        rbtnBuscarGrado3 = new javax.swing.JRadioButton();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);

        jLabel3.setText("Seleccione el grado a buscar");

        BuscarGrado.add(rbtnBuscarGrado1);
        rbtnBuscarGrado1.setText("Grado 1");

        BuscarGrado.add(rbtnBuscarGrado2);
        rbtnBuscarGrado2.setText("Grado 2");

        BuscarGrado.add(rbtnBuscarGrado3);
        rbtnBuscarGrado3.setText("Grado 3");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscar)
                    .addComponent(rbtnBuscarGrado3)
                    .addComponent(rbtnBuscarGrado2)
                    .addComponent(jLabel3)
                    .addComponent(rbtnBuscarGrado1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtnBuscarGrado1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtnBuscarGrado2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtnBuscarGrado3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscar)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        if(rbtnBuscarGrado1.isSelected()){
            mostrarEstudiantesPorGrado("Grado 1");
        }else if(rbtnBuscarGrado2.isSelected()){
            mostrarEstudiantesPorGrado("Grado 2");
        }else if(rbtnBuscarGrado3.isSelected()){
            mostrarEstudiantesPorGrado("Grado 3");
        }else {
            JOptionPane.showMessageDialog(this, "Seleccione un Grado a buscar");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed
    private void mostrarEstudiantesPorGrado(String nombreGrado){
        modeloTabla.setRowCount(0);
        List<Estudiante> filtrado = Grado.filtrarPorGrado(nombreGrado);
        
        for (Estudiante e : filtrado) {
            modeloTabla.addRow(new Object []{e.getNombreEstudiante(),e.getGradoEstudiante()});
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BuscarGrado;
    private javax.swing.ButtonGroup GradoEstudiante;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton rbtnBuscarGrado1;
    private javax.swing.JRadioButton rbtnBuscarGrado2;
    private javax.swing.JRadioButton rbtnBuscarGrado3;
    // End of variables declaration//GEN-END:variables
}
