/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ejemplologin;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author USER
 */
public class FrmPrincipal extends javax.swing.JFrame {

    String user;
    ArrayList<Usuario> listaUsuarios;
    int id, idProfile;

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal(String user, int id, int idProfile, ArrayList<Usuario> listaUsuarios) {
        initComponents();
        setLocationRelativeTo(null);
        this.user = user;
        this.id = id;
        this.idProfile = idProfile;
        this.listaUsuarios = listaUsuarios;
        lbUser.setText("Hola " + this.user);
        btnTouchMe.setEnabled(this.idProfile == 1);
        menuInformes.setVisible(this.idProfile == 1);
        scrollInfo.setVisible(this.idProfile == 1);
        btnAdmin.setVisible(this.idProfile != 1);
    }

    public void login() {
        JTextField usr = new JTextField();
        int actionLogin = JOptionPane.showConfirmDialog(null, usr, "Usuario", 
                JOptionPane.OK_CANCEL_OPTION);
        if (actionLogin > 0) {
            JOptionPane.showMessageDialog(null, "Operación cancelada");
        } else {
            JPasswordField pwd = new JPasswordField();
            int action = JOptionPane.showConfirmDialog(null, pwd, "Contraseña", 
                    JOptionPane.OK_CANCEL_OPTION);
            if (action > 0) {
                JOptionPane.showMessageDialog(null, "Operación cancelada");
            } else {
                String usuario = new String(usr.getText().toUpperCase());
                String passw = new String(pwd.getPassword());
                int id = 0;
                int idProfile = 0;
                for (int i = 0; i < listaUsuarios.size(); i++) {
                    if (listaUsuarios.get(i).getUser().equals(usuario)
                            && listaUsuarios.get(i).getPass().equals(passw)) {
                        id = listaUsuarios.get(i).getId();
                        idProfile = listaUsuarios.get(i).getIdProfile();
                    }
                }
                if (id != 0) {
                    scrollInfo.setVisible(true);
                    btnAdmin.setText("Logout");
                } else {
                    JOptionPane.showMessageDialog(this, "Usuario y/o Contreaseña Incorrectos", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbUser = new javax.swing.JLabel();
        btnTouchMe = new javax.swing.JButton();
        scrollInfo = new javax.swing.JScrollPane();
        tableInfo = new javax.swing.JTable();
        btnAdmin = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        itemCerrarSesion = new javax.swing.JMenuItem();
        menuInformes = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        lbUser.setText("jLabel1");

        btnTouchMe.setText("Touch me <3");

        tableInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollInfo.setViewportView(tableInfo);

        btnAdmin.setText("Admin");
        btnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminActionPerformed(evt);
            }
        });

        menuArchivo.setText("Archivo");

        itemCerrarSesion.setText("Cerrar Sesión");
        itemCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCerrarSesionActionPerformed(evt);
            }
        });
        menuArchivo.add(itemCerrarSesion);

        jMenuBar1.add(menuArchivo);

        menuInformes.setText("Informes");
        jMenuBar1.add(menuInformes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lbUser)
                    .addComponent(btnTouchMe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdmin)
                .addGap(0, 228, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTouchMe)
                    .addComponent(btnAdmin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        FrmLogin login = FrmLogin.getInstance();
        login.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void itemCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCerrarSesionActionPerformed
        // TODO add your handling code here:
        FrmLogin login = FrmLogin.getInstance();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_itemCerrarSesionActionPerformed

    private void btnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminActionPerformed
        // TODO add your handling code here:
        String textoBoton = btnAdmin.getText();
        if (textoBoton.equals("Admin")) {
            login();
        } else {
            scrollInfo.setVisible(false);
            btnAdmin.setText("Admin");
        }

    }//GEN-LAST:event_btnAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal(null, 0, 0, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdmin;
    private javax.swing.JButton btnTouchMe;
    private javax.swing.JMenuItem itemCerrarSesion;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lbUser;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenu menuInformes;
    private javax.swing.JScrollPane scrollInfo;
    private javax.swing.JTable tableInfo;
    // End of variables declaration//GEN-END:variables
}
